const categoriesData = {
  categories: [
    { id: 1, name: "Groceries" },
    { id: 2, name: "Shoes" },
    { id: 3, name: "Makeup" },
    { id: 4, name: "Electronics" },
    { id: 5, name: "Books" },
    { id: 6, name: "Clothing" },
    { id: 7, name: "Home Decor" },
    { id: 8, name: "Toys" },
    { id: 9, name: "Sports Equipment" },
    { id: 10, name: "Jewelry" },
    { id: 11, name: "Furniture" },
    { id: 12, name: "Pet Supplies" },
    { id: 13, name: "Art Supplies" },
    { id: 14, name: "Stationery" },
    { id: 15, name: "Kitchenware" },
    { id: 16, name: "Tools" },
    { id: 17, name: "Health Supplements" },
    { id: 18, name: "Baby Products" },
    { id: 19, name: "Outdoor Gear" },
    { id: 20, name: "Gardening Supplies" },
    { id: 21, name: "Party Supplies" },
    { id: 22, name: "Craft Supplies" },
    { id: 23, name: "Musical Instruments" },
    { id: 24, name: "Fitness Gear" },
    { id: 25, name: "Office Supplies" },
    { id: 26, name: "Travel Accessories" },
    { id: 27, name: "Board Games" },
    { id: 28, name: "Car Accessories" },
    { id: 29, name: "Bathroom Essentials" },
    { id: 30, name: "Computer Accessories" },
    { id: 31, name: "Cleaning Supplies" },
    { id: 32, name: "Cookware" },
    { id: 33, name: "DIY Materials" },
    { id: 34, name: "Laundry Products" },
    { id: 35, name: "Photography Gear" },
    { id: 36, name: "Camping Gear" },
    { id: 37, name: "School Supplies" },
    { id: 38, name: "Hair Care" },
    { id: 39, name: "Skincare" },
    { id: 40, name: "Home Appliances" },
    { id: 41, name: "Video Games" },
    { id: 42, name: "Puzzles" },
    { id: 43, name: "Outdoor Furniture" },
    { id: 44, name: "Sunglasses" },
    { id: 45, name: "Candles" },
    { id: 46, name: "Gourmet Food" },
    { id: 47, name: "Baking Supplies" },
    { id: 48, name: "Wine & Spirits" },
    { id: 49, name: "Hiking Gear" },
    { id: 50, name: "Yoga Accessories" },
    { id: 51, name: "Dancewear" },
    { id: 52, name: "Smart Home Devices" },
    { id: 53, name: "Tea & Coffee" },
    { id: 54, name: "Luggage" },
    { id: 55, name: "Dining Sets" },
    { id: 56, name: "Party Decorations" },
    { id: 57, name: "Painting Supplies" },
    { id: 58, name: "Gym Equipment" },
    { id: 59, name: "Binoculars" },
    { id: 60, name: "Cooking Utensils" },
    { id: 61, name: "Mobile Accessories" },
    { id: 62, name: "Plants & Flowers" },
    { id: 63, name: "Picnic Supplies" },
    { id: 64, name: "Car Parts" },
    { id: 65, name: "Fishing Gear" },
    { id: 66, name: "Board Games" },
    { id: 67, name: "Rugs" },
    { id: 68, name: "Craft Kits" },
    { id: 69, name: "Cosmetics Bags" },
    { id: 70, name: "Headphones" },
    { id: 71, name: "Wall Art" },
    { id: 72, name: "Strollers & Accessories" },
    { id: 73, name: "Bike Accessories" },
    { id: 74, name: "Action Figures" },
    { id: 75, name: "Party Games" },
    { id: 76, name: "Audio Equipment" },
    { id: 77, name: "Socks" },
    { id: 78, name: "Gift Cards" },
    { id: 79, name: "Cooking Books" },
    { id: 80, name: "Backpacks" },
    { id: 81, name: "Planners" },
    { id: 82, name: "Pillows" },
    { id: 83, name: "Air Fresheners" },
    { id: 84, name: "Hammocks" },
    { id: 85, name: "Cooking Classes" },
    { id: 86, name: "Mugs" },
    { id: 87, name: "Bluetooth Speakers" },
    { id: 88, name: "Dog Toys" },
    { id: 89, name: "Umbrellas" },
    { id: 90, name: "Embroidery Kits" },
    { id: 91, name: "Photo Albums" },
    { id: 92, name: "Stuffed Animals" },
    { id: 93, name: "Towels" },
    { id: 94, name: "Surfing Equipment" },
    { id: 95, name: "Dolls" },
    { id: 96, name: "Scooters" },
  ],
};

export default categoriesData;
